apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: client-app
  name: client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: client-app
    spec:
      containers:
      - image: brunton/craftsman-frontend
        imagePullPolicy: ""
        name: client-app
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
