apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server-app
  name: server-app
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  - name: "5001"
    port: 5001
    targetPort: 80
  selector:
    io.kompose.service: server-app
status:
  loadBalancer: {}
