apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/app-network: "true"
    io.kompose.service: server-app
  name: server-app
spec:
  containers:
  - image: brunton/craftsman-backend
    name: server-app
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
