apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-app
  name: client-app
spec:
  type: LoadBalancer
  ports:
    - name: '4200'
      port: 4200
      targetPort: 80
  selector:
    app: client-app
status:
  loadBalancer: {}
