apiVersion: v1
kind: Service
metadata:
  labels:
    app: craftsman-db
  name: craftsman-db
spec:
  ports:
    - name: '1433'
      port: 1433
      targetPort: 1433
  selector:
    app: craftsman-db
status:
  loadBalancer: {}
