apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-app
  name: server-app
spec:
  type: LoadBalancer
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  - name: "5001"
    port: 5001
    targetPort: 80
  selector:
    app: server-app
status:
  loadBalancer: {}
